version: "3.9"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
    - "5432:5432"
  web:
    build: .
    tty: true
    env_file:
      - .env
    command: gunicorn -c python:config.gunicorn config.wsgi
    working_dir: /app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
