version: "3.9"

services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    tty: true
    env_file:
      - .env
    command: gunicorn -c python:config.gunicorn config.wsgi
    working_dir: /app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - "${DOCKER_WEB_VOLUME}"
