name: "CI"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
      - "master"
      - "run_script"

jobs:
  test:
    runs-on: "ubuntu-20.04"

    steps:
      - uses: "actions/checkout@v2"
      - name: "Test"
        run: |
          ./run ci:test
        env:
          DOCKER_BUILDKIT: "1"
